config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root 'events#index'
  resources :events
  resources :attendances
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :date, :location, presence: true

  belongs_to :creator, class_name: "User"
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances

  scope :upcoming, -> { where("date > ?", Time.now) }
  scope :past, -> { where("date < ?", Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def new
    @attending = current_user.attendances.build
  end

  def create
    @attending = current_user.attendances.build(attendance_params)

    if @attending.save
      redirect_to events_path(Event.find(params[:id]))
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @attending = Attendance.find(params[:id])
    @attending.destroy

    redirect_to event_url
  end

  private
  def attendance_params
    params.require(:attendance).permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    if user_signed_in?
      @attendance = current_user.attendances.find_by attended_event_id: params[:id]
    end
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :date, :location, :private_event)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @created_events = current_user.created_events
    @attended_events = current_user.attended_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<h1>
  <%= event.title %>
</h1>
<p>
  <strong>Date: </strong>
  <%= event.date %>
</p>
<p>
  <strong>Location: </strong>
  <%= event.location %>
</p>

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :date %><br>
    <%= form.datetime_select :date, :ampm => true %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :private_event, "Make Event Private?" %>
    <%= form.check_box :private_event%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<p> *Private events can be viewed on your events page </p>

<h1>Upcoming Public Events</h1>
<div class="container">
  <% if @events.upcoming.empty? %>
    <%= link_to 'Create a new event', new_event_path, class: "event-container"%>
  <% end %>
  <% @events.upcoming.each do |event| %>
    <% unless event.private_event %>
      <%= link_to event, class: "event-container" do %>
        <%= render event %>
      <% end %>
    <% end %>
  <% end %>
</div>

<h1>Past Public Events</h1>
<div class="container">
  <% @events.past.each do |event| %>
    <% unless event.private_event %>
      <%= link_to event, class: "event-container" do %>
        <%= render event %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :date %><br>
    <%= form.datetime_select :date, :ampm => true %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<div>
  <%= render "event", event: @event %>

  <% if user_signed_in? %>
    <% if @attendance.nil? %>
      <%= button_to "Going", attendances_path, params: {
        'attendance[attended_event_id]': @event.id,
        'attendance[attendee_id]': current_user.id
      } %>
    <% else %>
      <%= button_to "Not Going", attendance_path(@attendance), method: :delete %>
    <% end %>

    <% if current_user.id == @event.creator_id %>
      <%= button_to "Edit Event", edit_event_path, method: :get %>
      <%= button_to "Delete Event", event_path(@event), method: :delete %>
    <% end %>
  <% else %>
    <%= button_to "Log in to join this event", new_user_session_path, method: :get %>
  <% end %>

  <%= button_to "Back to Events", events_path, method: :get %>

  <h2>Attendees</h2>
  <%  @event.attendances.each do |attendee| %>
    <p><%= attendee.attendee.username %><p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<ul class="navbar">
  <li class="<%= 'active' if current_page?(root_path) || current_page?(events_path) %> nav-item">
    <%= link_to 'Home', events_path, class: "nav-link" %>
  </li>
  <% if user_signed_in? %>
    <li class="<%= 'active' if current_page?(new_event_path) %> nav-item">
      <%= link_to 'Create Event', new_event_path, class: "nav-link" %>
    </li>
    <li class="<%= 'active' if current_page?(users_show_path) %> nav-item">
      <%= link_to 'Your Events', users_show_path, class: "nav-link" %>
    </li>
    <li class="nav-item align-right">
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete, data: { turbo_method: "delete" }, class: "nav-link" %>
    </li>
    <li class="<%= 'active' if current_page?(edit_user_registration_path) %> nav-item align-right">
      <%= link_to current_user.username, edit_user_registration_path, class: "nav-link" %>
    </li>
  <% else %>
    <li class="<%= 'active' if current_page?(user_session_path) %> nav-item align-right">
      <%= link_to 'Log In', user_session_path, class: "nav-link" %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= render 'layouts/navbar' %>

    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<h1>Events You Created</h1>
<div class="container">
  <% if @created_events.empty? %>
    <%= link_to 'Create a new event', new_event_path, class: "event-container"%>
  <% end %>
  <% @created_events.each do |event| %>
    <%= link_to event, class: "event-container" do %>
      <%= render event %>
    <% end %>
  <% end %>
</div>

<h1>Upcoming Events</h1>
<div class="container">
  <% if @attended_events.upcoming.empty? %>
    <%= link_to 'View existing events', events_path, class: "event-container" %>
  <% end %>
  <% @attended_events.upcoming.each do |event| %>
    <%= link_to event, class: "event-container" do %>
      <%= render event %>
    <% end %>
  <% end %>
</div>

<h1>Past Events</h1>
<div class="container">
  <% @attended_events.past.each do |event| %>
    <%= link_to event, class: "event-container" do %>
      <%= render event %>
    <% end %>
  <% end %>
</div>